name: Build and Test

on: [push, pull_request]

jobs:
  test:
    runs-on: [macos-latest, ubuntu-latest]
    name: Running Java ${{ matrix.java }} compile
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Compile code
      run: mvn -q clean test -Dlogging.level.edu.hawaii.its.casdemo=OFF -Dlogging.level.org.springframework=ERROR -Dspring.main.banner-mode=off